version: "3.9"
   
services:
  db:
    image: postgres
    container_name: "post_db"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - first
  web:
    container_name: "web"
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/project
    ports:
      - "8000:8000"
    depends_on:
      - db
    links:
      - db:db
    networks:
      - first

networks:
  first:
    name: first
    driver: bridge
