version: '3.7'

services:
  web:
    container_name: web
    build:
       context: .
       dockerfile: Dockerfile-production
    image: 887192593293.dkr.ecr.us-east-1.amazonaws.com/djangoanddocker:web
    command: gunicorn apps.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/bond/web/staticfiles
      - media_volume:/home/bond/web/mediafiles
    ports:
      - 8000
    env_file:
      - ./.env.prod
  nginx-proxy:
    container_name: nginx-proxy
    build: ./nginx
    image: 887192593293.dkr.ecr.us-east-1.amazonaws.com/djangoanddocker:nginx
    restart: always
    volumes:
      - static_volume:/home/bond/web/staticfiles
      - media_volume:/home/bond/web/mediafiles
      - certs:/etc/nginx/certs
      - html:/usr/share/nginx/html
      - vhost:/etc/nginx/vhost.d
      - /var/run/docker.sock:/tmp/docker.sock:ro
    ports:
      - 443:443
      - 80:80
    depends_on:
      - web
  nginx-proxy-letsencrypt:
    container_name: nginx-proxy-letsencrypt
    image: jrcs/letsencrypt-nginx-proxy-companion
    env_file:
      - .env.prod.proxy-companion
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - certs:/etc/nginx/certs
      - html:/usr/share/nginx/html
      - vhost:/etc/nginx/vhost.d
    depends_on:
      - nginx-proxy

volumes:
  postgres_data:
  static_volume:
  media_volume:
  certs:
  html:
  vhost:
